import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Profiles of people offering help (volunteers)
  volunteers: defineTable({
    name: v.string(),
    email: v.string(),
    category: v.union(v.literal("tech"), v.literal("idiomas")),
    rawOffer: v.string(), // free-form text of what they offer, as they said it
    profileSummary: v.string(), // structured summary generated by the LLM
    embedding: v.array(v.number()),
    availability: v.string(), // free-form text: "weekday afternoons", etc.
    verified: v.boolean(), // manual human approval before activating
    active: v.boolean(), // whether they're available to receive matches now
    createdAt: v.number(),
  })
    .index("by_category", ["category"])
    .index("by_active", ["active"]),

  // Help requests (people asking)
  requests: defineTable({
    name: v.string(),
    email: v.string(),
    category: v.union(v.literal("tech"), v.literal("idiomas")),
    rawNeed: v.string(), // free-form text of what they need
    needSummary: v.string(), // structured summary generated by the LLM
    embedding: v.array(v.number()),
    status: v.union(
      v.literal("buscando"), // waiting for a match
      v.literal("match_encontrado"), // match proposed, waiting for confirmation
      v.literal("confirmado"), // both sides accepted
      v.literal("completado"),
      v.literal("sin_match") // no one available was found
    ),
    matchedVolunteerId: v.optional(v.id("volunteers")),
    matchScore: v.optional(v.number()), // cosine similarity of the chosen match
    matchReasoning: v.optional(v.string()), // why the LLM chose this match
    roomUrl: v.optional(v.string()), // Daily.co link generated on confirmation
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_category", ["category"]),

  // Evaluation cases (to measure matching accuracy, a Nebius requirement)
  evalCases: defineTable({
    needText: v.string(),
    expectedCategory: v.string(),
    expectedMatchDescription: v.string(), // what a correct match looks like
    actualMatchDescription: v.optional(v.string()),
    wasCorrect: v.optional(v.boolean()),
    notes: v.optional(v.string()),
  }),
});
