import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Profiles of people offering help (volunteers)
  volunteers: defineTable({
    name: v.string(),
    email: v.string(),
    category: v.union(v.literal("tech"), v.literal("languages")),
    rawOffer: v.string(), // free-form text of what they offer, as they said it
    profileSummary: v.string(), // structured summary generated by the LLM
    embedding: v.array(v.number()),
    availability: v.string(), // free-form text: "weekday afternoons", etc.
    verified: v.boolean(), // manual human approval before activating
    active: v.boolean(), // whether they're available to receive matches now
    // Volunteer validation: LinkedIn identity + minimum-knowledge quiz.
    // Optional so existing seeded rows keep working; new registrations
    // always set them, and approve() rejects rows that lack them.
    linkedinUrl: v.optional(v.string()),
    quizScore: v.optional(v.number()), // correct answers out of QUIZ_LENGTH
    skillLevel: v.optional(
      v.union(v.literal("beginner"), v.literal("intermediate"), v.literal("advanced"))
    ),
    // Two-sided matching: how many matches this volunteer already served.
    // Congestion control demotes over-matched volunteers so the load spreads.
    matchCount: v.optional(v.number()),
    languages: v.optional(v.string()), // languages they can help in
    // True for AI helpers: clearly-labeled instant fallback when no human
    // is available. Demoted in scoring so humans always win when present.
    isVirtual: v.optional(v.boolean()),
    createdAt: v.number(),
  })
    .index("by_category", ["category"])
    .index("by_active", ["active"]),

  // Help requests (people asking)
  requests: defineTable({
    name: v.string(),
    email: v.string(),
    category: v.union(v.literal("tech"), v.literal("languages")),
    rawNeed: v.string(), // free-form text of what they need
    needSummary: v.string(), // structured summary generated by the LLM
    embedding: v.array(v.number()),
    status: v.union(
      v.literal("searching"), // waiting for a match
      v.literal("match_found"), // match proposed, waiting for confirmation
      v.literal("confirmed"), // both sides accepted
      v.literal("completed"),
      v.literal("no_match"), // no one available was found
      v.literal("failed") // the pipeline errored (e.g. upstream timeout)
    ),
    matchedVolunteerId: v.optional(v.id("volunteers")),
    matchScore: v.optional(v.number()), // cosine similarity of the chosen match
    matchReasoning: v.optional(v.string()), // why the LLM chose this match
    roomUrl: v.optional(v.string()), // Daily.co link generated on confirmation
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_category", ["category"]),

  // Evaluation cases (to measure matching accuracy, a Nebius requirement)
  evalCases: defineTable({
    needText: v.string(),
    expectedCategory: v.string(),
    expectedMatchDescription: v.string(), // what a correct match looks like
    actualMatchDescription: v.optional(v.string()),
    wasCorrect: v.optional(v.boolean()),
    notes: v.optional(v.string()),
    isAdversarial: v.optional(v.boolean()), // highlights the "cosine alone would be wrong" case
    // Populated by convex/evalRunner.ts when the case is run against the
    // live pipeline -- lets the eval dashboard show real latency/cost, not
    // just accuracy, matching the track's "measure accuracy, latency, or
    // cost" requirement.
    topCandidateByCosineOnly: v.optional(v.string()), // what pure similarity alone would have picked
    chosenByLLM: v.optional(v.string()), // what the LLM decision layer actually picked
    llmReasoning: v.optional(v.string()),
    latencyMs: v.optional(v.number()), // full pipeline: close profile + embed + decide
    estimatedTokens: v.optional(v.number()),
    lastRunAt: v.optional(v.number()),
  }),
});
