import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Profiles of people offering help (volunteers)
  volunteers: defineTable({
    name: v.string(),
    email: v.string(),
    category: v.union(v.literal("tech"), v.literal("languages")),
    rawOffer: v.string(), // free-form text of what they offer, as they said it
    profileSummary: v.string(), // structured summary generated by the LLM
    embedding: v.array(v.number()),
    availability: v.string(), // free-form text: "weekday afternoons", etc.
    verified: v.boolean(), // manual human approval before activating
    active: v.boolean(), // whether they're available to receive matches now
    // Volunteer validation: LinkedIn identity + minimum-knowledge quiz.
    // Optional so existing seeded rows keep working; new registrations
    // always set them, and approve() rejects rows that lack them.
    linkedinUrl: v.optional(v.string()),
    quizScore: v.optional(v.number()), // correct answers out of QUIZ_LENGTH
    skillLevel: v.optional(
      v.union(v.literal("beginner"), v.literal("intermediate"), v.literal("advanced"))
    ),
    // Two-sided matching: how many matches this volunteer already served.
    // Congestion control demotes over-matched volunteers so the load spreads.
    matchCount: v.optional(v.number()),
    languages: v.optional(v.string()), // languages they can help in
    // True for AI helpers: clearly-labeled instant fallback when no human
    // is available. Demoted in scoring so humans always win when present.
    isVirtual: v.optional(v.boolean()),
    // Structured weekly availability ("mon-evening", ...). Free-text
    // `availability` stays for humans; these ids are what matching verifies.
    slots: v.optional(v.array(v.string())),
    // Reputation: sum/count of 1-5 ratings from requesters (avg = sum/count).
    // Feeds the match card and a small matching bonus for proven volunteers.
    ratingSum: v.optional(v.number()),
    ratingCount: v.optional(v.number()),
    // Reliability: how many times a confirmed session died on their side.
    // At 3 strikes the volunteer is auto-paused (active=false) — the teeth
    // ADPList's no-show flow famously lacks.
    noShowCount: v.optional(v.number()),
    // Public track record: finished sessions + latest written review,
    // denormalized here so the directory renders without extra queries.
    completedCount: v.optional(v.number()),
    latestReview: v.optional(v.string()),
    latestReviewer: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_category", ["category"])
    .index("by_active", ["active"])
    .index("by_email", ["email"]),

  // Help requests (people asking)
  requests: defineTable({
    name: v.string(),
    email: v.string(),
    category: v.union(v.literal("tech"), v.literal("languages")),
    rawNeed: v.string(), // free-form text of what they need
    needSummary: v.string(), // structured summary generated by the LLM
    embedding: v.array(v.number()),
    status: v.union(
      v.literal("searching"), // waiting for a match
      v.literal("match_found"), // match proposed, waiting for confirmation
      v.literal("confirmed"), // both sides accepted
      v.literal("completed"),
      v.literal("no_match"), // no one available was found
      v.literal("failed") // the pipeline errored (e.g. upstream timeout)
    ),
    matchedVolunteerId: v.optional(v.id("volunteers")),
    matchScore: v.optional(v.number()), // cosine similarity of the chosen match
    matchReasoning: v.optional(v.string()), // why the LLM chose this match
    roomUrl: v.optional(v.string()), // Daily.co link generated on confirmation
    // Requester-side duration: how long they need (15/30/60). Requesters may
    // ask for something quick; the 1-hour minimum applies to volunteers only.
    expectedMinutes: v.optional(v.number()),
    // Scheduling: when they want the session (free choice from set slots).
    // Shown on the match so both sides coordinate; rooms generate on confirm.
    preferredTime: v.optional(v.string()),
    // Structured version of the above: slot ids the request overlaps with,
    // plus the requester's timezone for honest display. Empty = "as soon as
    // possible", no time constraint applied.
    preferredSlots: v.optional(v.array(v.string())),
    preferredTz: v.optional(v.string()),
    // Post-session ratings (1-5), one per side. The requester rates the
    // volunteer and vice versa, from the shared status link. No auth: each
    // side can only write its own field once (guarded in submitRating).
    requesterRating: v.optional(v.number()),
    volunteerRating: v.optional(v.number()),
    // Written review (≤280 chars) attached to the requester's rating.
    // Mirrored onto the volunteer as latestReview for the directory.
    requesterReview: v.optional(v.string()),
    // Session template picked at intake ("resume-review", ...) and the
    // volunteer a recurring user asked for again (matching boost).
    template: v.optional(v.string()),
    preferredVolunteerId: v.optional(v.id("volunteers")),
    // Attendance check-in (ms timestamps): each side taps "I'm here" from
    // the shared status link. The sweep auto-flags whoever never checked in
    // once the no-show window expires. Self-declared (no auth in v1).
    requesterHereAt: v.optional(v.number()),
    volunteerHereAt: v.optional(v.number()),
    // Detected user language (en/es/fr/zh...). Matching data stays in
    // English, but everything the user reads renders in this language.
    language: v.optional(v.string()),
    // True for AI virtual volunteers: skip Daily.co video room, use Aria AI helper instead.
    isVirtual: v.optional(v.boolean()),
    // Stored intake history so a no-show requeue can re-run matching
    // without asking the person to repeat the conversation.
    history: v.optional(
      v.array(v.object({ role: v.string(), content: v.string() }))
    ),
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_category", ["category"])
    .index("by_email", ["email"]),

  // Evaluation cases (to measure matching accuracy, a Nebius requirement)
  evalCases: defineTable({
    needText: v.string(),
    expectedCategory: v.string(),
    expectedMatchDescription: v.string(), // what a correct match looks like
    actualMatchDescription: v.optional(v.string()),
    wasCorrect: v.optional(v.boolean()),
    notes: v.optional(v.string()),
    isAdversarial: v.optional(v.boolean()), // highlights the "cosine alone would be wrong" case
    // Populated by convex/evalRunner.ts when the case is run against the
    // live pipeline -- lets the eval dashboard show real latency/cost, not
    // just accuracy, matching the track's "measure accuracy, latency, or
    // cost" requirement.
    topCandidateByCosineOnly: v.optional(v.string()), // what pure similarity alone would have picked
    chosenByLLM: v.optional(v.string()), // what the LLM decision layer actually picked
    llmReasoning: v.optional(v.string()),
    latencyMs: v.optional(v.number()), // full pipeline: close profile + embed + decide
    estimatedTokens: v.optional(v.number()),
    lastRunAt: v.optional(v.number()),
  }),

  // Time credits ledger (1 hour given = 1 credit earned, 1 credit = 1 hour
  // claimed). Keyed by email since there is no auth; balances move only
  // inside the request lifecycle (charge on create, earn on complete).
  balances: defineTable({
    email: v.string(),
    balance: v.number(),
  }).index("by_email", ["email"]),

  // Group sessions: a volunteer hosts one room for up to `capacity`
  // requesters on a shared template (ADPList-style: resume review, mock
  // interview). Members join by email (no auth); the room generates once
  // the host confirms the group.
  groups: defineTable({
    volunteerId: v.id("volunteers"),
    title: v.string(),
    category: v.union(v.literal("tech"), v.literal("languages")),
    template: v.string(),
    slots: v.array(v.string()),
    capacity: v.number(),
    members: v.array(v.object({ name: v.string(), email: v.string() })),
    status: v.union(
      v.literal("open"),
      v.literal("ready"),
      v.literal("closed")
    ),
    roomUrl: v.optional(v.string()),
    roomError: v.optional(v.string()),
    roomAttempts: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_category", ["category"]),

  // Communities: TimeRepublik-style themed groups. Members join by email;
  // the directory of volunteers can be filtered by community later.
  communities: defineTable({
    name: v.string(),
    description: v.string(),
    category: v.optional(v.union(v.literal("tech"), v.literal("languages"))),
    memberEmails: v.array(v.string()),
    createdAt: v.number(),
  }).index("by_name", ["name"]),
});
